### ISSUE TITLE
[Bug]: hat textures, even original ones are not working

### ISSUE THREAD

**Issue by Pajik001** [ZombieStriker/QualityArmory-Resourcepack#6]
### Confirmations

- [X] I am using the latest plugin version with the required dependencies.
- [X] There isn't any open issue that shows my problem

### What happened?

I added 101 new hats and every hat broke, even the "original ones" [Now its purple-black cube]

additional info:
Ammo is broken too, so the "phantom_membrane" is propably somehow broken

### Expected Behaviour

That hat works

### Plugins

Reviveme (This one support QA)

### Server Version

1.18.2

**Comment by Lorenzo0111** [comment]
Are you able to provide the resourcepack you created?

**Comment by Pajik001** [comment]
> Are you able to provide the resourcepack you created?

Issue fixed, forgot to delete issue
